INSERT INTO tb_category(name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Clothing', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Home Appliances', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Toys', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Furniture', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Food', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sports', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Automotive', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Beauty', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Health', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Music', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Movies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Jewelry', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Gaming', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Photography', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Art', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Pets', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Books & Magazines', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Kitchenware', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Gardening', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Stationery', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Crafts', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Outdoor', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Hobbies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Books for Kids', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Luxury', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Tech Gadgets', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Shoes', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Mobile Phones', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Watches', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Collectibles', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Travel', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Fitness', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Camping', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Adventure', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Music Instruments', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Craft Beverages', NOW());
